name: Publish
on:
  schedule:
  - cron: '0 0 * * *'
jobs:
  publish:
    name: Publish
    if: github.repository == 'dcodeIO/long.js'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: main
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx aspublish
